### ISSUE TITLE
Named export 'BroadcastChannel' not found when using with vite-ssg

### ISSUE THREAD

**Issue by MihaiVoinea** [wobsoriano/pinia-shared-state#11]
Hi!

I get this error when using pinia-shared-state with vite-ssg.

```
web:build: import{watch as h}from"vue-demi";import{BroadcastChannel as b}from"broadcast-channel";function p(a,n,{initialize:d,type:s="native"}){let e=`${n.$id}-${a.toString()}`,r=new b(e,{type:s}),l=!1,i=0;h(()=>n[a],t=>{l||(i=Date.now(),r.postMessage({timestamp:i,state:t})),l=!1},{deep:!0}),r.onmessage=t=>{if(t===void 0){r.postMessage({timestamp:i,state:n[a]});return}t.timestamp<=i||(l=!0,i=t.timestamp,n[a]=t.state)};let o=()=>r.postMessage(void 0),c=()=>r.close();return d&&o(),{sync:o,unshare:c}}var y=(a,n)=>Object.keys(n).includes(a),$=({initialize:a=!0,enable:n=!0,type:d="native"})=>({store:s,options:e})=>{var i,o,c,t;let r=(o=(i=e==null?void 0:e.share)==null?void 0:i.enable)!=null?o:n,l=(t=(c=e==null?void 0:e.share)==null?void 0:c.omit)!=null?t:[];!r||Object.keys(s.$state).forEach(u=>{var m,f;l.includes(u)||!y(u,s.$state)||p(u,s,{initialize:(f=(m=e==null?void 0:e.share)==null?void 0:m.initialize)!=null?f:a,type:d})})};export{$ as PiniaSharedState,p as share};
web:build:                                         ^^^^^^^^^^^^^^^^
web:build: SyntaxError: Named export 'BroadcastChannel' not found. The requested module 'broadcast-channel' is a CommonJS module, which may not support all module.exports as named exports.
web:build: CommonJS modules can always be imported via the default export, for example using:
web:build:
web:build: import pkg from 'broadcast-channel';
web:build: const {watch: h}from"vue-demi";import{BroadcastChannel: b}from"broadcast-channel";function p(a,n,{initialize:d,type:s="native"}){let e=`${n.$id}-${a.toString()}`,r=new b(e,{type:s}),l=!1,i=0;h(()=>n[a],t=>{l||(i=Date.now(),r.postMessage({timestamp:i,state:t})),l=!1},{deep:!0}),r.onmessage=t=>{if(t===void 0){r.postMessage({timestamp:i,state:n[a]});return}t.timestamp<=i||(l=!0,i=t.timestamp,n[a]=t.state)};let o=()=>r.postMessage(void 0),c=()=>r.close();return d&&o(),{sync:o,unshare:c}}var y=(a,n)=>Object.keys(n).includes(a),$=({initialize:a=!0,enable:n=!0,type:d="native"})=>({store:s,options:e})=>{var i,o,c,t;let r=(o=(i=e==null?void 0:e.share)==null?void 0:i.enable)!=null?o:n,l=(t=(c=e==null?void 0:e.share)==null?void 0:c.omit)!=null?t:[];!r||Object.keys(s.$state).forEach(u=>{var m,f;l.includes(u)||!y(u,s.$state)||p(u,s,{initialize:(f=(m=e==null?void 0:e.share)==null?void 0:m.initialize)!=null?f:a,type:d})})};export{$: PiniaSharedState,p: share} = pkg;
web:build:
web:build:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
web:build:     at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
web:build:     at async Promise.all (index 0)
web:build:     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
web:build:     at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
web:build:     at async Object.build (/home/mihai/repos/heyusers/node_modules/vite-ssg/dist/chunks/build.cjs:171:87)
web:build:     at async Object.handler (/home/mihai/repos/heyusers/node_modules/vite-ssg/dist/node/cli.cjs:25:3)
web:build: error Command failed with exit code 1.
web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web:build: Error: command finished with error: command (web) yarn run build exited (1)
```

Is this some incompatibility with how pinia-shared-state imports broadcast-channel?

Could you help me in any way to fix this? I tried dynamically importing pinia-shared-state only when vite-ssg is not running, that fixed the error but pinia-shared-state was not working anymore then.

Thanks!

**Comment by wobsoriano** [comment]
thanks!

https://github.com/wobsoriano/pinia-shared-state/releases/tag/v0.2.4
